name: pip freeze
description: Freeze pip packages

inputs:
  pip_cli_options:
    description: Options to pass to the pip command
    required: false
    default: "--verbose"

  requirements-file:
    description: Path to the requirements file
    required: false
    default: ./requirements.frozen.txt

runs:
  using: "composite"
  steps:
    - name: pip freeze > ${{ inputs.requirements-file }}
      shell: bash
      run: |
        pip freeze
        pip freeze > ${{ inputs.requirements-file }}
