name: pip install
description: Upgrade pip packages

inputs:
  pip_cli_options:
    description: Options to pass to the pip command
    required: false
    default: "--verbose"

  requirements-file:
    description: Path to the requirements file
    required: false
    default: ./requirements.txt

  package:
    description: Install a package
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: pip install -r ${{ inputs.requirements-file }}
      shell: bash
      run: pip install ${{ inputs.pip_cli_options }} --requirement ${{ inputs.requirements-file }}

    - name: pip install .
      shell: bash
      if: ${{ inputs.package == 'true' }}
      run: pip install ${{ inputs.pip_cli_options }} .
